# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
tensor = torch.rand(7,7)
tensor
# Create random tensor


tensor([[0.0948, 0.9523, 0.2493, 0.6544, 0.9837, 0.4946, 0.2484],
        [0.8998, 0.9945, 0.0709, 0.8475, 0.2711, 0.3366, 0.6859],
        [0.3035, 0.4353, 0.6003, 0.2275, 0.2374, 0.5114, 0.2586],
        [0.0663, 0.2079, 0.8047, 0.4663, 0.9103, 0.3756, 0.8237],
        [0.2178, 0.5665, 0.4784, 0.5884, 0.3288, 0.9738, 0.0893],
        [0.1764, 0.5494, 0.2225, 0.0421, 0.5680, 0.4217, 0.1517],
        [0.4492, 0.0360, 0.7070, 0.4915, 0.9695, 0.9371, 0.2900]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_2 = torch.rand(1,7)
tensor_2
# Perform matrix multiplication
torch.matmul(tensor,tensor_2.T)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [2]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)

# Create two random tensors
tensor_a = torch.rand(7,7)
tensor_b = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor_a,tensor_b.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [3]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [4]:
# Set random seed
random_seed = 1234
torch.manual_seed(random_seed)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_a = torch.rand(2,3).to(device)
tensor_b = torch.rand(2,3).to(device)
tensor_a,tensor_b

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [5]:
# Perform matmul on tensor_A and tensor_B
tensor_c = torch.matmul(tensor_a,tensor_b.T)
tensor_c,tensor_c.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max = tensor_c.max()
# Find min
min = tensor_c.min()
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
max_index = tensor_c.argmax()

# Find arg min
min_index = tensor_c.argmin()
max_index, min_index


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed

random_seed = 7
torch.manual_seed(random_seed)
# Create random tensor
tensor_a = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_a_remove = tensor_a.squeeze()

# Print out tensors and their shapes
tensor_a,tensor_a_remove,tensor_a.shape,tensor_a_remove.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]))