<a href="https://colab.research.google.com/github/XinyaoT/pytorch-deep-learning/blob/main/mynotes/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas
import numpy as np
print(torch.__version__)

2.5.1+cu121


In [ ]:
!nvidia-smi

Thu Nov 21 13:45:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## tensor
### create tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item

<function Tensor.item>

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape,matrix.size()

(torch.Size([2, 2]), torch.Size([2, 2]))

###Random tensor


In [ ]:
# creat random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor.ndim

2

###zero and ones

In [ ]:
zero = torch.zeros(size =(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### arange of tensor

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(0,10)
torch.arange(start = 0,end = 1000,step = 77)



tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# tensor like----相同的形状的全零张量
ten_zeros = torch.zeros_like(input =one_to_ten )
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###张量的datatype
####**note**:三个深度学习常见报错
1. tensor not right type——tensor.dtype
2. tensor not right shape——tensor.shape
3. tensor not right device——tensor.device

In [ ]:
# float32
float_32_tensor = torch.tensor([3,9,6])
float_32_tensor

tensor([3, 9, 6])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)  #把32的精度转换成16的精度
float_16_tensor

tensor([3., 9., 6.], dtype=torch.float16)

###张量的三个属性


In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device of tensor:{some_tensor.device}")

tensor([[0.7135, 0.5199, 0.6948, 0.3347],
        [0.8949, 0.5887, 0.5372, 0.0578],
        [0.1070, 0.7754, 0.2862, 0.5001]])
datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device of tensor:cpu


###张量的计算
1. 加法
2. 减法
3. 乘法
4. 除法
5. 矩阵运算

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

###矩阵运算
1. 外积——对应位置相乘
2. 内积（点积）


In [ ]:
tensor * tensor
print(f"equal:{tensor*tensor}")

equal:tensor([1, 4, 9])


In [ ]:
%%time
# tensor.matmul(tensor)
torch.matmul(tensor,tensor)

CPU times: user 91 µs, sys: 0 ns, total: 91 µs
Wall time: 95.8 µs


tensor(14)

###矩阵乘法的三个规则
1. 内部维度必须相同
2. 结果和外部维度相同

In [ ]:
# 转置——transpose
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_mul= torch.mm(tensor_A,tensor_B.T)

In [ ]:
tensor_mul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###找最大、最小、平均、求和

In [ ]:
torch.max(tensor_mul)


tensor(117)

In [ ]:
torch.min(tensor_mul)


tensor(27)

In [ ]:
# 以下两种表达方式相同
torch.mean(tensor_mul.type(torch.float32))


tensor(68.)

In [ ]:
tensor_mul.type(torch.float32).mean()

tensor(68.)

In [ ]:
tensor_mul.sum()

tensor(612)

###找到位置的最大和最小

In [ ]:
tensor_mul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_mul.argmin()

tensor(0)

In [ ]:
tensor_mul.argmax()

tensor(8)

In [ ]:
tensor_mul[0][0]

tensor(27)

### reshape、stacking、squeezing、unsqueezing tensor
1. reshape的形状要与原来的形状兼容——乘积相同
2. view函数创建出来的reshape后的向量和和原始向量共享存储空间，所以他改变，原始向量也会改变
3. stack堆叠函数，堆叠的所有函数必须拥有相同的形状
4. permute维度的重排列,也是共享内存的，重排列前后的都是

In [ ]:

import torch
x = torch.arange(1.,10.)
x = torch.arange(start = 1.,end = 10.,step=1)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
x_reshaped = x.reshape(10,1)
x_reshaped,x_reshaped.shape

RuntimeError: shape '[10, 1]' is invalid for input of size 9

In [ ]:
# view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# squeeze
x_reshaped.shape


torch.Size([3, 3])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [ ]:
x_reshaped=x_reshaped.reshape(1,9)


In [ ]:
x_squeezed = x_reshaped.squeeze()

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"previous tensor:{x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")
print(f"new tensor:{x_unsqueezed}")
print(f"new shape:{x_unsqueezed.shape}")


previous tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])
new tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new shape:torch.Size([9, 1])


In [ ]:
# permute
x_original = torch.rand(size = (224,224,3))#长、宽、通道
x_permuted = x_original.permute(2,0,1)# 通道、长、宽
print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])


In [ ]:
x_permuted[0,0,0] = 1
x_permuted,x_original


(tensor([[[1.0000, 0.5267, 0.7782,  ..., 0.4785, 0.8949, 0.6317],
          [0.2638, 0.2553, 0.1962,  ..., 0.0128, 0.3719, 0.3658],
          [0.7799, 0.2908, 0.2354,  ..., 0.1225, 0.6817, 0.1423],
          ...,
          [0.4876, 0.2660, 0.9973,  ..., 0.3907, 0.4342, 0.6213],
          [0.6904, 0.6539, 0.5652,  ..., 0.9896, 0.7531, 0.5640],
          [0.5393, 0.9007, 0.3417,  ..., 0.3182, 0.9344, 0.3603]],
 
         [[0.6411, 0.6431, 0.1769,  ..., 0.2168, 0.8943, 0.6602],
          [0.2004, 0.5065, 0.3044,  ..., 0.9241, 0.3065, 0.7589],
          [0.7812, 0.9514, 0.9578,  ..., 0.6512, 0.3450, 0.5582],
          ...,
          [0.5336, 0.9711, 0.9311,  ..., 0.3591, 0.6602, 0.4667],
          [0.9885, 0.7545, 0.0710,  ..., 0.5401, 0.4359, 0.8647],
          [0.7051, 0.2397, 0.7125,  ..., 0.8818, 0.5437, 0.0992]],
 
         [[0.7162, 0.2202, 0.0549,  ..., 0.5606, 0.7504, 0.5146],
          [0.0483, 0.4553, 0.9549,  ..., 0.5584, 0.4705, 0.3437],
          [0.8512, 0.1027, 0.6312,  ...,

### 索引


In [ ]:
import torch
x  = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[:,:,0]
# :表示对应维度全部都取

tensor([[1, 4, 7]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[:,0:1,1]

tensor([[2]])

In [ ]:
# 对比以下的两种取法：
#通过下面的例子理解：全部都取，0是只去了一维，这两个取下来tensor的size不同
x[:,1,1]

tensor([5])

In [ ]:
x[0,1,1]

tensor(5)

In [ ]:
# challenge
# 9
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
# 3.6.9
x[:,:,2]

tensor([[3, 6, 9]])

##numpy & tensor
1. numpy->tensor:torch.from_numpy(ndarry)
* numpy默认float64，tensor默认float32
* 采用这种方法转换后，原始数据共享内存，改变ndarry，tensor也会改变
2. tensor->numpy:torch.Tensor.numpy()
* 与上述现象一致，包括共享内存和运算的内存机制


In [ ]:
1.
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype,tensor.dtype
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
array[0] = 5
array,tensor

(array([5., 2., 3., 4., 5., 6., 7.]),
 tensor([5., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# array运算不会改变tensor
array+1,tensor

(array([6., 3., 4., 5., 6., 7., 8.]),
 tensor([5., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

####解释上述现象：
在 NumPy 中，执行 array + 1 并不会直接修改原数组的值，而是创建一个新的数组，用于存放计算结果。这种操作会在内存中重新分配一块区域存储新数组，而不是在原数组上进行修改。
所以内存上还是共享的

In [ ]:
# tensor->numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor[0] = 7
tensor,numpy_tensor

(tensor([7., 1., 1., 1., 1., 1., 1.]),
 array([7., 1., 1., 1., 1., 1., 1.], dtype=float32))

### reproducibility（take random out of random）可再现性

In [ ]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.5051, 0.1233, 0.5897, 0.7492],
        [0.5998, 0.6168, 0.1270, 0.4009],
        [0.5726, 0.7532, 0.4357, 0.7544]])
tensor([[0.2500, 0.2000, 0.1800, 0.8686],
        [0.7675, 0.6968, 0.4795, 0.3973],
        [0.8278, 0.9557, 0.2271, 0.4025]])


In [ ]:
# seed
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


### device running on GPUs
* 常见的device设置语句

In [ ]:
! nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!nvidia-smi


Mon Nov 25 13:38:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# set up device
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of device
torch.cuda.device_count()

1

### putting tensor and model on the GPU

In [ ]:

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPUs
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# move tensors from GPUS to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])